app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin, db.Model):
    '''
    defining subject
    '''
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    password_hash = db.Column(db.String(255))
    

    @property
    def password(self):
        raise AttributeError('Cannot read the password')


    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'Pitch {self.username}'

class Pitch(db.Model):
    '''
    Defining a pitch
    '''
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    body = db.Column(db.String)
    author = db.Column(db.String)
    category = db.Column(db.String)
    upvotes = db.Column(db.Integer)
    downvotes = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    posted = db.Column(db.DateTime, default=datetime.utcnow)

    def save_pitches(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls):
        pitches = Pitch.query.all()
        return pitches

    @classmethod
    def get_categories(cls, category):
        pitch_cat = Pitch.query.filter_by(category=category)
        return pitch_cat

    all_pitches = []

    def __init__(self,title,body,author,category,upvotes,downvotes,user_id):
        self.title = title
        self.body = body
        self.author = author
        self.category = category
        self.upvotes = upvotes
        self.downvotes = downvotes
        self.user_id = user_id

class Comment(db.Model):
    '''
    defining pitch object
    '''
    __tablename__= 'comments'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    comment = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls):
        comments = Comment.query.all()
        return comments

    all_comments = []

    def __init__(self,title,comment,user):
        self.title = title
        self.comment = comment
        self.user = user

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, RadioField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField('Pitch title', validators=[Required()])
    author = TextAreaField('Enter your comment here', validators=[Required()])
    body = StringField('Author', validators=[Required()])
    category = RadioField('Pick cateory', choices=[('wired', 'wired')], validators=[Required()])
    submit = SubmitField('submit')



class CommentForm(FlaskForm):
    title = StringField('title', validators=[Required()])
    comment = TextAreaField('comment', validators=[Required()])
    submit = SubmitField('Submit')

class Vote(FlaskForm):
    rating = RadioField('Rate this pitch', choices=[('upvote','upvote'), ('downvote','downvote')],validators=[Required()])


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us more about you', validators=[Required()])

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_simplemde import SimpleMDE
from flask_bootstrap import Bootstrap

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

#configurations
db = SQLAlchemy()
photos = UploadSet('photos', IMAGES)
simple = SimpleMDE()
bootstrap = Bootstrap()



def create_app(config_name):

    #initializing app
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    #initializing flask extensions
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)
    bootstrap.init_app(app)

    #Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    configure_uploads(app, photos)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from .forms import PitchForm, CommentForm, Vote
from ..models import User, Pitch, Comment
from flask_login import login_required, current_user
from .. import db, photos


@main.route('/')
def index():
    '''
    Function that renders the index.html and its functions
    '''
    pitches = Pitch.query.all()

    return render_template('index.html', pitches=pitches)

@main.route('/')
def wired():
    '''
    function that renders the category wired and its functions
    '''
    wired_pitch = Pitch.query.filter_by(category='wired').all()

    return render_template('wired.html', wired=wired_pitch)

@main.route('/')
def business():
    '''
    function that renders the category wired and its functions
    '''
    business_pitch = Pitch.query.filter_by(category='wired').all()

    return render_template('business.html', business=business_pitch)


@main.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    pitch_form = PitchForm()

    if pitch_form.validate_on_submit():
        title = pitch_form.title.data
        body = pitch_form.body.data
        author = pitch_form.author.data
        category = pitch_form.category.data

        new_pitch = Pitch(title=title, body=body, author=author, category=category, upvotes=0, downvotes=0, users=current_user)
        new_pitch.save_pitches()
        return redirect(url_for('main.index'))

    return render_template('new.html', pitch_form=pitch_form)

@main.route('/comment/<int:id>', methods=['GET', 'POST'])
@login_required
def comment(id):
    comment_form = CommentForm()
    vote_radio = Vote()
    pitch = Pitch.query.get(id)
    if comment_form.validate_on_submit():
        title = comment_form.title.data
        comment = comment_form.comment.data

        new_comment = Comment(comment=comment,title=title,user=current_user)
        new_comment.save_comment()
        return redirect(url_for('main.index'))


    return render_template('comment.html',comment_form=comment_form,pitch=pitch,vote_radio=vote_radio)

# @main.route('/update', methods=['POST'])
# def update():
#     pitch = Pitch.query.get(id)
#     pitch.upvotes = request.args.get('jsdata')
#     pitch.downvotes = request.args.get('jsdata')

#     return render_template('button.html', pitch=pitch)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    '''
    Function rendering the profile page for our user
    '''
    user = User.query.filter_by(username=uname).first()


    if user is None:
        abort(404)

    return render_template('profile/profile.html', user=user)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()

    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  <link rel="stylesheet" href="/static/index.css">
  <title>Welcome to Pitch</title>
  <script type="text/javascript">
    var voteClicks = function (votes) {
      return votes += 1
    }
    $(document).ready(function() {
      $(document).on('click', '.btn', function() {
        var btn_id = $(this).attr('btn_id')
        // console.log(btn_id);
        var votes = $('#pitch'+ btn_id).text()
        // console.log(votes);
        int_votes = voteClicks(parseInt(votes))
        console.log(int_votes)
        str_votes = int_votes.toString()
        req = $.ajax({
          url: '/update',
          type: 'get',
          data: {jsdata:int_votes}
        });
        req.done(function(data){
          new_votes=$('#pitch'+ btn_id).text(str_votes)
          $('#pitch.pitch.id').html(data)
        });
      });
    });
  </script>

  <script src="{{url_for('static',filename='js/script.js')}}"></script>
</head>
<body>
        {% block navbar %} {% include 'navbar.html' %} {% endblock %}

        {% block content %} {% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/buttons.html
<a href="#" id="pitch{{pitch.upvotes}}" class="btn btn-primary btn-lg" btn_id="{{(pitch.upvotes)}}"><i class="far fa-hand-point-up mr-2"></i>{{pitch.upvotes}}</a>
<a href="#" id="pitch{pitch.downvotes}}" class="btn btn-primary btn-lg"btn_id="{{(pitch.downvotes)}}"><i class="far fa-hand-point-down mr-2"></i>{{pitch.downvotes}}</a>

app/templates/categories.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
                {{macro.displayCategory(category)}}
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html' %} {% block styles %} {{super()}} {{simple.css}} {{simple.js}} {% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="panel-header">
            {{pitch.title}}
        </div>
        <div class="panel-body">
            <p>{{pitch.body}}</p>
            <strong>{{pitch.author}}</strong>
            <form action method="post" class='form' role='form'>
                {{vote_radio.rating.label}}
        </div>
        <div class="row form-check form-check-inline ">
            {{vote_radio.hidden_tag()}} {{vote_radio.rating(class_='form-check-input')}}
        </div>
    </div>
    </form>
    <form action method="post" class='form' role='form'>
        <div class="row mt-3">
            {{comment_form.title.label}}
        </div>
        <div class="row">
            {{comment_form.hidden_tag()}} {{comment_form.title(class_='form-control', placeholder="write a comment")}}
        </div>
        <div class="row mt-3">
            {{comment_form.comment.label}}
        </div>
        <div class="row">
            {{comment_form.hidden_tag()}} {{comment_form.comment(class_='form-control', placeholder="Tell us what you think")}} {{ simplemde.load
            }}
        </div>
        <div class="row mt-3">
            {{comment_form.submit(class_="btn btn-outline-primary")}}
        </div>
    </form>
    {{ simplemde.load }} {% endblock %}


</div>

app/templates/index.html
{% extends 'base.html' %} {% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles %} {% endblock %}


<!-- Content block -->
{% block content %}
<div class="container-fluid mt-3">
  <p>Do you want to write a pitch. Sign up <a href="auth/login">here</a></p>
  <p>Already signed in? Write a pitch <a href="/new">here</a>.</p>
  <div class="row">
      {{macro.displayPitchList(pitches)}}
  </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %} {% for pitch in pitch_list %}
<div class="col-xs-6 col-sm-6 col-md-6">
  <div class="card m-2">
    <div class="card-header">
      Category - {{pitch.category}}
    </div>
    <div class="card-body">
      <h5 class="card-title">{{pitch.title}}</h5>
      <p class="card-text">{{pitch.body}}</p>
      <p class="card-text"><small class="text-muted">{{pitch.author}}</small></p>
      <hr>
      <p>Add a comment <a href="/comment/{{pitch.id}}">here</a>.</p>
    </div>
  </div>
</div>
{% endfor %} {% endmacro %}

app/templates/navbar.html
{% import 'macros.html' as macro %}
<nav class="navbar navbar-expand-lg navbar-light" style="background:linear-gradient(-90deg, #00ccff, #00ffff, #00ccff);">
  <a class="navbar-brand" href="/">Pitch</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        </a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    </ul>
  </div>
</nav>

app/templates/new.html
{% extends 'base.html' %}
{% block styles %}
  {{super()}}
  <!-- Importing simple mde css and js files  -->
  {{simple.css}}
  {{simple.js}}
{% endblock %}


{% block content %}
<div class="container new-pitch">
  <h3>Write a pitch</h3>
  <form action method="post" class='form' role='form'>
    <div class="row mt-3">
      {{pitch_form.title.label}}
    </div>
    <div class="row">
      {{pitch_form.hidden_tag()}} {{pitch_form.title(class_='form-control', placeholder="Enter title")}}
    </div>
    <div class="row mt-3">
      {{pitch_form.body.label}}
    </div>
    <div class="row">
      {{pitch_form.hidden_tag()}} {{pitch_form.body(class_='form-control', placeholder="Who is the author?")}}
      {{ simplemde.load }}
    </div>
    <div class="row mt-3">
      {{pitch_form.author.label}}
    </div>
    <div class="row">
      {{pitch_form.hidden_tag()}} {{pitch_form.author(class_='form-control', placeholder="Your Pitch")}}
    </div>
    <div class="row mt-3">
      {{pitch_form.category.label}}
    </div>
    <div class="row form-check form-check-inline ">
      {{pitch_form.hidden_tag()}} {{pitch_form.category(class_='form-check-input')}}
    </div>
    <div class="row">
      {{pitch_form.submit(class_="btn btn-outline-primary")}}
    </div>
  </form>
  {{ simplemde.load }}
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<div class="container">

<div class="row">


  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">

    </form>
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %}